def draw_hangman(mistakes):
    if mistakes == 0:
        print( "")
        print( "")
        print( "")
        print( "")
        print( "")
        print( "")
        print( "")
        print( "")
        print( "")
        print( "")
        print( "")
        print( "")
        print( "     __________________")
        print( "")
    if mistakes == 1:
        print( "          __________")
        print( "         |         |")
        print( "         |         |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "      _____________|_____")
        print( "                           ")
    if mistakes == 2:
        print( "          __________")
        print( "         |         |")
        print( "         |         |")
        print( "       _/_\_       |")
        print( "        |_|        |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "      _____________|_____")
        print( "                           ")
    if mistakes == 3:
        print( "          __________")
        print( "         |         |")
        print( "         |         |")
        print( "       _/_\_       |")
        print( "        |_|        |")
        print( "         |         |")
        print( "      ---|         |")
        print( "         |         |")
        print( "         |         |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "      _____________|_____")
        print( "                           ")
    if mistakes == 4:
        print( "          __________")
        print( "         |         |")
        print( "         |         |")
        print( "       _/_\_       |")
        print( "        |_|        |")
        print( "         |         |")
        print( "      ---|---      |")
        print( "         |         |")
        print( "         |         |")
        print( "                   |")
        print( "                   |")
        print( "                   |")
        print( "      _____________|_____")
        print( "                           ")
    if mistakes == 5:
        print( "          __________")
        print( "         |         |")
        print( "         |         |")
        print( "       _/_\_       |")
        print( "        |_|        |")
        print( "         |         |")
        print( "      ---|---      |")
        print( "         |         |")
        print( "         |         |")
        print( "        /          |")
        print( "       /           |")
        print( "                   |")
        print( "      _____________|_____")
        print( "                           ")
    if mistakes == 6:
        print( "          __________")
        print( "         |         |")
        print( "         |         |")
        print( "       _/_\_       |")
        print( "        |_|        |")
        print( "         |         |")
        print( "      ---|---      |")
        print( "         |         |")
        print( "         |         |")
        print( "        / \        |")
        print( "       /   \       |")
        print( "                   |")
        print( "      _____________|_____")
        print( "                           ")
